### ISSUE TITLE
新建知识库时可能出现问题

### ISSUE THREAD

**Issue by NL127** [Lealand23231513/SciAgent#20]
1.本地知识库在新建的时候 如果填入了知识库的名字但是没填api key就新建，会导致error，但是这个库的名字仍然会存在于更改知识库一栏中，如果选择更改这个为选中的本地知识库或者删除这个库，都会error，vscode上显示错误类型是did not find openai api key, 同时也不能再建立和这个库同名的知识库
2.在新建本地知识库时，如果填入了不合法的名字（如AA）,和上面类似地，尽管在新建的时候会error，但是仍然存在于下面选择知识库的选项中，且既不能更改为选中的本地知识库，也不能删除
<img width="946" alt="4c1507befd879210c0e485874ee374e" src="https://github.com/Lealand23231513/SciAgent/assets/142155618/c263fdf2-f526-432b-b774-4b1d4072bfd4">

<img width="922" alt="29be4d6a55fdbdfae74dcd8ddb804f3" src="https://github.com/Lealand23231513/SciAgent/assets/142155618/69f8f1d4-ec92-4c4b-8dea-4aa857b94334">

**Comment by Lealand23231513** [comment]
@NL127 谢谢你的反馈，我已经修改了，你可以试试现在能否正常使用

**Comment by NL127** [comment]
试了一下  应该是解决了，不会建成不合法的知识库；辛苦了!
