### ISSUE TITLE
一次openai api key未填写导致后续填上后也报错did not find openai api key

### ISSUE THREAD

**Issue by NL127** [Lealand23231513/SciAgent#21]
在使用Agent和PDF文档问答两个页面时，如果中间有某次提交时没有填写api key， 则后续即使填上了api key,仍然不能正常运行，显示error并报错 did not find openai api key。这个问题在视觉问答页面中没有看到出现。
<img width="1092" alt="1711253095536" src="https://github.com/Lealand23231513/SciAgent/assets/142155618/22801775-d81c-4122-a107-e4a25224689b">
![image](https://github.com/Lealand23231513/SciAgent/assets/142155618/8761ec4c-48d9-4318-a02e-1b29dd31c287)

**Comment by Lealand23231513** [comment]
@NL127 已经更新了一遍，现在这个问题还存在吗？

**Comment by Lealand23231513** [comment]
solved
